In [1]:
#importing Numpy library
import numpy as np

In [3]:
# creating one-dimensional Numpy array arr from a Python list
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [11]:
# Create a 3D NumPy array representing weekly sales data from a list of lists .  
# The dimensions of the array are structured as follows:  
# - The three dimension represents different weeks (1st week to 4th week).  
sales_data = np.array([[[250,300,400],[200,250,350]],[[260,310,410],[210,260,360]],[[270,320,420],[220,270,370]],[[280,330,430],[230,280,380]]])
print("3D Array : \n" , sales_data)
print("Shape: " , sales_data.shape)

3D Array : 
 [[[250 300 400]
  [200 250 350]]

 [[260 310 410]
  [210 260 360]]

 [[270 320 420]
  [220 270 370]]

 [[280 330 430]
  [230 280 380]]]
Shape:  (4, 2, 3)


In [15]:
# create a two-dimensional Numpy array arr1 from a list of two lists.
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [19]:
# create a two-dimensional Numpy array zeros from a list of two lists with default value of zero.
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
# create a three-dimensional Numpy array ones from a list of three lists with default value of one.
ones = np.ones((3,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [27]:
# create a one-dimensional array of integers from 0 to 9 using np.arange().
range_array = np.arange(10)
print(range_array)

[0 1 2 3 4 5 6 7 8 9]


In [31]:
#create an array with values starting from 0 up to (but not including) 10, with a step size of 2.
range_step = np.arange(0,10,2)
print(range_step)

[0 2 4 6 8]


In [37]:
#generating a sequence of five numbers over a specified interval from 0 to 1.
linespace_array = np.linspace(0,1,5)
print(linespace_array)

[0.   0.25 0.5  0.75 1.  ]


In [41]:
#Creating an Array with Random Values Between 0 and 1
random_array = np.random.rand(3,3)
print(random_array)

[[0.28936965 0.9080998  0.36836677]
 [0.93689009 0.49433902 0.11628099]
 [0.51270097 0.44319565 0.27984416]]


In [45]:
#create a 2x2 array with random integers between 1 and 9
random_integers = np.random.randint(1,10,(2,2))
print(random_integers)

[[9 9]
 [4 3]]


In [47]:
arrr = np.array([[1,2,3],[4,5,6]])
print(arrr.shape)#return the shape of the array, showing it has 2 rows and 3 columns

(2, 3)


In [49]:
print(arrr.dtype)#check the data type of elements in the array, showing that they are 32-bit integers.

int32


In [53]:
#accesses elements in the array by their index. 
array = np.array([10,20,30,40,50])
print(array[0])
print(array[-1])

10
50


In [57]:
#slices the array to get a subarray from index 1 to 3. 
print(array[1:4])

[20 30 40]


In [69]:
#indexing 2D Array 
mat = np.array(([5,10,20],[20,25,30],[35,40,10]))
print("the matrix : \n",mat,"\n")
print("the second row of matrix : \n ",mat[1],"\n")
print("the third element of the third row is : \n", mat[2][2])

the matrix : 
 [[ 5 10 20]
 [20 25 30]
 [35 40 10]] 

the second row of matrix : 
  [20 25 30] 

the third element of the third row is : 
 10
